---
title: "Schulz_2020_Nature"
author: "Jeffrey Blanchard"
date: "12/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DT)
```

```{r}
Schulz_2020_Nature <- read_tsv("Schulz_2020_Nature.tsv")
```
```{r}
Schulz_2020_Nature %>% 
# filter(Location == "Harvard Forest") %>% 
ggplot(aes(x = rank, y = assembly_size, size = Location, color = Location, fill = Location )) + 
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.8) +
  scale_size_manual(values = c(6, 1)) +
 # scale_fill_manual(values = c("Other" = "grey", "Harvard Forest" = "magenta")) +
 # scale_color_manual(values = c("Other" = "black", "Harvard Forest" = "magenta")) +
  ggtitle("Rank genome size of 2278 Nucleocytoviricota MAGs in Schulz et al. 2020 Nature") +
  ylab("Genome size") + 
  xlim(c(0,2300)) +
  xlab("Rank") +
  theme(text = element_text(size = 20, color="black")) 
#  theme(axis.text.x = element_text(angle = 90)) 
```

```{r}
Schulz_2020_Nature %>% 
 filter(Location == "Harvard Forest") %>% 
ggplot(aes(x = rank, y = assembly_size, color = Location, fill = Location )) + 
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.5, size = 2) +
  scale_fill_manual(values = c("Other" = "white", "Harvard Forest" = "magenta")) +
  scale_color_manual(values = c("Other" = "white", "Harvard Forest" = "magenta")) +
  ggtitle("Genome size of MAGs for each Class") +
  ylab("Genome size") + 
  xlab("Class") +
  xlim(c(0,2300)) +
 # theme(text = element_text(size = 20, color="black"))
  theme(axis.text.x = element_text(angle = 90)) 
```


```{r}
Schulz_2020_Nature %>% 
# filter(Location == "Harvard Forest") %>% 
ggplot(aes(x = assembly_size, fill = Location )) + 
  geom_histogram(binwidth=50000) +
  ggtitle("Histogram of MAG size") +
  scale_fill_manual(values = c("Other" = "white", "Harvard Forest" = "magenta")) +
  ylab("Number") + 
  xlab("Genome Size") +
  theme(text = element_text(size = 20, color="black")) 
 # theme(text = element_text(size = 20, color="black"))
 # theme(axis.text.x = element_text(angle = 90)) 
```



```{r}
Schulz_2020_Nature_filter <- read_tsv("Schulz_2020_Nature_filter.tsv")
```

```{r}
Schulz_2020_Nature_filter %>% 
# filter(Location == "Harvard Forest") %>% 
ggplot(aes(x = rank, y = assembly_size, size = Location, color = Location, fill = Location )) + 
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.8) +
  scale_size_manual(values = c(6, 6, 1)) +
#  scale_fill_manual(values = c("Other" = "grey", "Harvard Forest" = "magenta", "filter" = "blue")) +
#  scale_color_manual(values = c("Other" = "black", "Harvard Forest" = "magenta", "filter" = "blue")) +
#  ggtitle("Rank genome size of 2278 Nucleocytoviricota MAGs in Schulz et al. 2020 Nature") +
  ylab("Genome size") + 
  xlim(c(0,2300)) +
  xlab("Rank") +
  theme(text = element_text(size = 20, color="black")) 
#  theme(axis.text.x = element_text(angle = 90)) 
```


